name: Issue
on:
  issue_comment:
    types: [created]

jobs:
  approval:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '[testpypi]') && (github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'COLLABORATOR')
    steps:
      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Validate Status
        run: |
          set -eo
          html_url="${{ github.event.issue.html_url }}"
          pr_url="https://github.com/${{ github.repository }}/pull"
          is_pr="$(python -c "print('$html_url'.startswith('$pr_url'))")"

          # add_comment "some comment data in $1"
          function add_comment() {
            curl -X POST \
                 --url '${{ github.event.issue.comments_url }}' \
                 -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
                 -H 'Content-Type: application/json' \
                 -d "{\"body\": \"$1\"}"
          }

          # add_reaction "reaction_type"
          #
          # reaction_type can be:
          #   "+1", "-1", "laugh", "confused", "heart", "hooray", "rocket", "eyes"
          function add_reaction() {
            curl -X POST \
               --url 'https://api.github.com/repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions' \
               -H 'Accept: application/vnd.github.squirrel-girl-preview' \
               -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
               -H 'Content-Type: application/json' \
               -d "{\"content\": \"$1\"}"
          }

          if [ "$is_pr" = "True" ]; then
            if [ "${{ github.event.issue.state }}" = "closed" ]; then
              # Add a comment to the issue indicating [testpypi] only triggers
              # for open pull requests.
              add_comment ':scream: `[testpypi]` only runs on **open** pull requests!'
              add_reaction "confused"
            else
              add_comment ':scream: :boom: :alien: :boom: :scream:'
              add_reaction "rocket"
            fi
          else
            add_comment ':no_entry_sign: `[testpypi]` only applies to open pull requests.'
            add_reaction "confused"
          fi
